# Generated by Django 5.2.6 on 2025-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_previews/'),
        ),
    ]
