# Generated by Django 5.2.6 on 2025-10-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover_book_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='preview_image',
        ),
    ]
