# Generated by Django 5.2.6 on 2025-10-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
